In [15]:
# Imports
import numpy as np
from scipy.sparse import csr_matrix, save_npz
import pandas as pd

## Part 1: Initial Processing

In [ ]:
fm_df = pd.read_csv("data\Last.fm_data.csv", index_col=0)
fm_df.head()

<>:3: SyntaxWarning: invalid escape sequence '\L'
<>:3: SyntaxWarning: invalid escape sequence '\L'
C:\Users\charl\AppData\Local\Temp\ipykernel_7860\602478312.py:3: SyntaxWarning: invalid escape sequence '\L'
  fm_df = pd.read_csv("data\Last.fm_data.csv", index_col=0)

,Username,Artist,Track,Album,Date,Time
0,Babs_05,Isobel Campbell,The Circus Is Leaving Town,Ballad of the Broken Seas,31 Jan 2021,23:36
1,Babs_05,Isobel Campbell,Dusty Wreath,Ballad of the Broken Seas,31 Jan 2021,23:32
2,Babs_05,Isobel Campbell,Honey Child What Can I Do?,Ballad of the Broken Seas,31 Jan 2021,23:28
3,Babs_05,Isobel Campbell,It's Hard To Kill A Bad Thing,Ballad of the Broken Seas,31 Jan 2021,23:25
4,Babs_05,Isobel Campbell,Saturday's Gone,Ballad of the Broken Seas,31 Jan 2021,23:21

In [16]:
# Inspect the DataFrame
print(fm_df.shape)
print(fm_df.columns.tolist())
print(fm_df.dtypes)

(166153, 6)
['Username', 'Artist', 'Track', 'Album', 'Date', 'Time']
Username    object
Artist      object
Track       object
Album       object
Date        object
Time        object
dtype: object

In [19]:
# Set column types
fm_df['Username'] = fm_df['Username'].astype('category')
fm_df['Artist'] = fm_df['Artist'].astype('category')

In [20]:
# Drop unnecessary columns
fm_df = fm_df.drop(columns=['Track','Album','Date','Time'])

In [23]:
# Check column names
print(fm_df.columns.tolist())
print(fm_df.dtypes)

['Username', 'Artist']
Username    category
Artist      category
dtype: object

## Part 2: Grouping

In [29]:
grouped = fm_df.groupby(['Username', 'Artist'])
grouped.head()

C:\Users\charl\AppData\Local\Temp\ipykernel_7860\2167361849.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = fm_df.groupby(['Username', 'Artist'])

       Username             Artist
0       Babs_05    Isobel Campbell
1       Babs_05    Isobel Campbell
2       Babs_05    Isobel Campbell
3       Babs_05    Isobel Campbell
4       Babs_05    Isobel Campbell
...         ...                ...
265612  Orlenay            ROSALÍA
265625  Orlenay  Caterina Barbieri
265626  Orlenay  Caterina Barbieri
265627  Orlenay  Caterina Barbieri
265628  Orlenay  Caterina Barbieri

[100476 rows x 2 columns]

In [31]:
grouped.value_counts().head(10)

Username  Artist
Babs_05   !!!                                                         0
          !Akimbo                                                     0
          "Blue" Gene Tyranny                                         0
          "Demons"                                                    1
          "Jesus Christ Superstar" Apostles - Original Studio Cast    0
          "Puppy Dog Pals" Cast                                       0
          "Weird Al" Yankovic                                         7
          #1 Garth Brooks Tribute Band                                2
          $NOT                                                        0
          $OUDIERE                                                    0
Name: count, dtype: int64